apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: test-lxcfs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: httpd:2.4.32
        # imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            # cpu: "500m"
            cpu: 1
          limits:
            memory: "256Mi"
            # cpu: "500m"
            cpu: 1
        volumeMounts:
        - mountPath: /dev/shm
          name: cache-volume
      volumes:
        # shm size
      - emptyDir:
          medium: Memory
          sizeLimit: 128Mi
        name: cache-volume